### ISSUE TITLE
[git] hash doesn't update correctly

### ISSUE THREAD

**Issue by Samega7Cattac** [Samega7Cattac/s7c.zsh-theme#1]

**Comment by unixorn** [comment]
Can you attach a log for this?

**Comment by Samega7Cattac** [comment]
when entering a repo directory it doesn't show the hash, but if I call zsh inside the directory is shows.
if I switch to another repo directory it shows the hash from the previous repo, not the current.
material about it is to make from scratch and it's around 11 years old and since they have a git plugin built in I tho it would update the vars on path change

**Comment by Samega7Cattac** [comment]
opened an issue https://github.com/ohmyzsh/ohmyzsh/issues/9274

**Comment by Samega7Cattac** [comment]
@unixorn the issue as been fixed
tell me what do u think
I will close this for now
