### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [Samega7Cattac/s7c.zsh-theme#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Samega7Cattac** [comment]
hi
I'm still struggling with #1 since I got no response from ohmyzsh on discord and this seems too trivial to open an issue on the repo.

**Comment by Samega7Cattac** [comment]
readme added with screenshot
and license also added
